// <auto-generated />
using System;
using Focadu.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Focadu.Infrastructure.Migrations
{
    [DbContext(typeof(FocaduDbContext))]
    [Migration("20260821220024_AddMarketplaceAndReferrals")]
    partial class AddMarketplaceAndReferrals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Focadu.Domain.Activities.ActivityResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("AiFeedback")
                        .HasColumnType("text");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DailyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justification")
                        .HasColumnType("text");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Transcript")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DailyId", "ActivityId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("ActivityResponses", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Activities.DailyActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedAnswer")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("DailyTemplateId");

                    b.ToTable("DailyActivities", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Activities.QuizOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("QuizOptions", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Activities.RoleplayNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<string>("NodeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TerminalQuality")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "NodeKey")
                        .IsUnique();

                    b.ToTable("RoleplayNodes", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Activities.RoleplayOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NextNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NextNodeId");

                    b.HasIndex("NodeId");

                    b.ToTable("RoleplayOptions", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Content.CuratedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BodyText")
                        .HasColumnType("text");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WeeklyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyTemplateId");

                    b.ToTable("CuratedContents", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Cosmetics.CosmeticItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AssetUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsAnimated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PriceGems")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("CosmeticItems", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Cosmetics.UserCosmeticInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CosmeticItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CosmeticItemId");

                    b.HasIndex("UserId", "CosmeticItemId")
                        .IsUnique();

                    b.ToTable("UserCosmeticInventories", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Cosmetics.UserEquippedCosmetics", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EquippedBannerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EquippedFrameId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EquippedNameColorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EquippedBannerId");

                    b.HasIndex("EquippedFrameId");

                    b.HasIndex("EquippedNameColorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserEquippedCosmetics", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Dailies.Daily", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DailyTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsReinforcement")
                        .HasColumnType("boolean");

                    b.Property<int>("PenaltyPoints")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReinforcementDailyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ReinforcementTriggered")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WeeklyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DailyTemplateId");

                    b.HasIndex("ReinforcementDailyId");

                    b.HasIndex("WeeklyId", "DayNumber")
                        .IsUnique();

                    b.ToTable("Dailies", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Dailies.DailyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WeeklyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyTemplateId", "DayNumber")
                        .IsUnique();

                    b.ToTable("DailyTemplates", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Enrollments.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Gamification.UserGemBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CurrentMonthPeriod")
                        .HasColumnType("date");

                    b.Property<int>("GemsFromDailiesThisMonth")
                        .HasColumnType("integer");

                    b.Property<int>("GemsFromMonthlyThisMonth")
                        .HasColumnType("integer");

                    b.Property<int>("GemsFromWeekliesThisMonth")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGems")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserGemBalances", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Gamification.UserStreak", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LastCompletedDate")
                        .HasColumnType("date");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStreaks", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Monthlies.Monthly", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Number")
                        .IsUnique();

                    b.ToTable("Monthlies", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Referrals.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReferredUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferrerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReferredUserId")
                        .IsUnique();

                    b.HasIndex("ReferrerUserId");

                    b.ToTable("Referrals", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalProfileNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.PrimitiveCollection<string[]>("Interests")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProfileCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ReferralCode")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.ModulePublication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("GeneratedDraft")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("WeeklyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyId")
                        .IsUnique();

                    b.ToTable("ModulePublications", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.Weekly", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("WeeklyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyTemplateId");

                    b.HasIndex("EnrollmentId", "WeeklyTemplateId")
                        .IsUnique();

                    b.ToTable("Weeklies", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.WeeklyProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SubmissionUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("WeeklyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyId")
                        .IsUnique();

                    b.ToTable("WeeklyProjects", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.WeeklyReinforcement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WeeklyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyId");

                    b.ToTable("WeeklyReinforcements", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.WeeklyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MonthlyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Theme")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WeeklyProjectSpecText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyId", "Number")
                        .IsUnique();

                    b.ToTable("WeeklyTemplates", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Activities.ActivityResponse", b =>
                {
                    b.HasOne("Focadu.Domain.Dailies.Daily", null)
                        .WithMany("Responses")
                        .HasForeignKey("DailyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Activities.DailyActivity", b =>
                {
                    b.HasOne("Focadu.Domain.Content.CuratedContent", null)
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Focadu.Domain.Dailies.DailyTemplate", null)
                        .WithMany("Activities")
                        .HasForeignKey("DailyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Activities.QuizOption", b =>
                {
                    b.HasOne("Focadu.Domain.Activities.DailyActivity", null)
                        .WithMany("QuizOptions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Activities.RoleplayNode", b =>
                {
                    b.HasOne("Focadu.Domain.Activities.DailyActivity", null)
                        .WithMany("RoleplayNodes")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Activities.RoleplayOption", b =>
                {
                    b.HasOne("Focadu.Domain.Activities.RoleplayNode", null)
                        .WithMany()
                        .HasForeignKey("NextNodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Focadu.Domain.Activities.RoleplayNode", null)
                        .WithMany("Options")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Content.CuratedContent", b =>
                {
                    b.HasOne("Focadu.Domain.Weeklies.WeeklyTemplate", null)
                        .WithMany("CuratedContents")
                        .HasForeignKey("WeeklyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Cosmetics.UserCosmeticInventory", b =>
                {
                    b.HasOne("Focadu.Domain.Cosmetics.CosmeticItem", null)
                        .WithMany()
                        .HasForeignKey("CosmeticItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Focadu.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Cosmetics.UserEquippedCosmetics", b =>
                {
                    b.HasOne("Focadu.Domain.Cosmetics.CosmeticItem", null)
                        .WithMany()
                        .HasForeignKey("EquippedBannerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Focadu.Domain.Cosmetics.CosmeticItem", null)
                        .WithMany()
                        .HasForeignKey("EquippedFrameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Focadu.Domain.Cosmetics.CosmeticItem", null)
                        .WithMany()
                        .HasForeignKey("EquippedNameColorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Focadu.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Dailies.Daily", b =>
                {
                    b.HasOne("Focadu.Domain.Dailies.DailyTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("DailyTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Focadu.Domain.Dailies.Daily", null)
                        .WithMany()
                        .HasForeignKey("ReinforcementDailyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Focadu.Domain.Weeklies.Weekly", null)
                        .WithMany("Dailies")
                        .HasForeignKey("WeeklyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Focadu.Domain.Dailies.DailyTemplate", b =>
                {
                    b.HasOne("Focadu.Domain.Weeklies.WeeklyTemplate", null)
                        .WithMany("DailyTemplates")
                        .HasForeignKey("WeeklyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Focadu.Domain.Enrollments.Enrollment", b =>
                {
                    b.HasOne("Focadu.Domain.Courses.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Focadu.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Gamification.UserGemBalance", b =>
                {
                    b.HasOne("Focadu.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Gamification.UserStreak", b =>
                {
                    b.HasOne("Focadu.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Monthlies.Monthly", b =>
                {
                    b.HasOne("Focadu.Domain.Courses.Course", null)
                        .WithMany("Monthlies")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Referrals.Referral", b =>
                {
                    b.HasOne("Focadu.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReferredUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Focadu.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReferrerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.ModulePublication", b =>
                {
                    b.HasOne("Focadu.Domain.Weeklies.Weekly", null)
                        .WithOne("Publication")
                        .HasForeignKey("Focadu.Domain.Weeklies.ModulePublication", "WeeklyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.Weekly", b =>
                {
                    b.HasOne("Focadu.Domain.Enrollments.Enrollment", null)
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Focadu.Domain.Weeklies.WeeklyTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("WeeklyTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.WeeklyProject", b =>
                {
                    b.HasOne("Focadu.Domain.Weeklies.Weekly", null)
                        .WithOne("Project")
                        .HasForeignKey("Focadu.Domain.Weeklies.WeeklyProject", "WeeklyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.WeeklyReinforcement", b =>
                {
                    b.HasOne("Focadu.Domain.Weeklies.Weekly", null)
                        .WithMany("Reinforcements")
                        .HasForeignKey("WeeklyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Focadu.Domain.Weeklies.WeakDailyLink", "_weakDailyLinks", b1 =>
                        {
                            b1.Property<Guid>("WeeklyReinforcementId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DailyId")
                                .HasColumnType("uuid");

                            b1.HasKey("WeeklyReinforcementId", "DailyId");

                            b1.HasIndex("DailyId");

                            b1.ToTable("WeeklyReinforcementWeakDailies", (string)null);

                            b1.HasOne("Focadu.Domain.Dailies.Daily", null)
                                .WithMany()
                                .HasForeignKey("DailyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("WeeklyReinforcementId");
                        });

                    b.Navigation("_weakDailyLinks");
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.WeeklyTemplate", b =>
                {
                    b.HasOne("Focadu.Domain.Monthlies.Monthly", null)
                        .WithMany("WeeklyTemplates")
                        .HasForeignKey("MonthlyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Activities.DailyActivity", b =>
                {
                    b.Navigation("QuizOptions");

                    b.Navigation("RoleplayNodes");
                });

            modelBuilder.Entity("Focadu.Domain.Activities.RoleplayNode", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Focadu.Domain.Courses.Course", b =>
                {
                    b.Navigation("Monthlies");
                });

            modelBuilder.Entity("Focadu.Domain.Dailies.Daily", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Focadu.Domain.Dailies.DailyTemplate", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Focadu.Domain.Monthlies.Monthly", b =>
                {
                    b.Navigation("WeeklyTemplates");
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.Weekly", b =>
                {
                    b.Navigation("Dailies");

                    b.Navigation("Project");

                    b.Navigation("Publication");

                    b.Navigation("Reinforcements");
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.WeeklyTemplate", b =>
                {
                    b.Navigation("CuratedContents");

                    b.Navigation("DailyTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
