// <auto-generated />
using System;
using Focadu.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Focadu.Infrastructure.Migrations
{
    [DbContext(typeof(FocaduDbContext))]
    [Migration("20260818172559_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Focadu.Domain.Activities.ActivityResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("AiFeedback")
                        .HasColumnType("text");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Transcript")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("ActivityResponses", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Activities.DailyActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedAnswer")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("DailyId");

                    b.ToTable("DailyActivities", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Activities.QuizOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("QuizOptions", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Activities.RoleplayNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<string>("NodeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TerminalQuality")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "NodeKey")
                        .IsUnique();

                    b.ToTable("RoleplayNodes", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Activities.RoleplayOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NextNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NextNodeId");

                    b.HasIndex("NodeId");

                    b.ToTable("RoleplayOptions", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Content.CuratedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyText")
                        .HasColumnType("text");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WeeklyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyId");

                    b.ToTable("CuratedContents", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Dailies.Daily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsReinforcement")
                        .HasColumnType("boolean");

                    b.Property<int>("PenaltyPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("ReinforcementTriggered")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WeeklyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyId", "DayNumber")
                        .IsUnique();

                    b.ToTable("Dailies", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Monthlies.Monthly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Number")
                        .IsUnique();

                    b.ToTable("Monthlies", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.Weekly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MonthlyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Theme")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyId", "Number")
                        .IsUnique();

                    b.ToTable("Weeklies", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.WeeklyProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("SpecText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SubmissionUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("WeeklyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyId")
                        .IsUnique();

                    b.ToTable("WeeklyProjects", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.WeeklyReinforcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WeeklyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyId");

                    b.ToTable("WeeklyReinforcements", (string)null);
                });

            modelBuilder.Entity("Focadu.Domain.Activities.ActivityResponse", b =>
                {
                    b.HasOne("Focadu.Domain.Activities.DailyActivity", null)
                        .WithMany("Responses")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Activities.DailyActivity", b =>
                {
                    b.HasOne("Focadu.Domain.Content.CuratedContent", null)
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Focadu.Domain.Dailies.Daily", null)
                        .WithMany("Activities")
                        .HasForeignKey("DailyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Activities.QuizOption", b =>
                {
                    b.HasOne("Focadu.Domain.Activities.DailyActivity", null)
                        .WithMany("QuizOptions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Activities.RoleplayNode", b =>
                {
                    b.HasOne("Focadu.Domain.Activities.DailyActivity", null)
                        .WithMany("RoleplayNodes")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Activities.RoleplayOption", b =>
                {
                    b.HasOne("Focadu.Domain.Activities.RoleplayNode", null)
                        .WithMany()
                        .HasForeignKey("NextNodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Focadu.Domain.Activities.RoleplayNode", null)
                        .WithMany("Options")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Content.CuratedContent", b =>
                {
                    b.HasOne("Focadu.Domain.Weeklies.Weekly", null)
                        .WithMany("CuratedContents")
                        .HasForeignKey("WeeklyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Dailies.Daily", b =>
                {
                    b.HasOne("Focadu.Domain.Weeklies.Weekly", null)
                        .WithMany("Dailies")
                        .HasForeignKey("WeeklyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Monthlies.Monthly", b =>
                {
                    b.HasOne("Focadu.Domain.Courses.Course", null)
                        .WithMany("Monthlies")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.Weekly", b =>
                {
                    b.HasOne("Focadu.Domain.Monthlies.Monthly", null)
                        .WithMany("Weeklies")
                        .HasForeignKey("MonthlyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.WeeklyProject", b =>
                {
                    b.HasOne("Focadu.Domain.Weeklies.Weekly", null)
                        .WithOne("Project")
                        .HasForeignKey("Focadu.Domain.Weeklies.WeeklyProject", "WeeklyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.WeeklyReinforcement", b =>
                {
                    b.HasOne("Focadu.Domain.Weeklies.Weekly", null)
                        .WithMany("Reinforcements")
                        .HasForeignKey("WeeklyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Focadu.Domain.Weeklies.WeakDailyLink", "_weakDailyLinks", b1 =>
                        {
                            b1.Property<Guid>("WeeklyReinforcementId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DailyId")
                                .HasColumnType("uuid");

                            b1.HasKey("WeeklyReinforcementId", "DailyId");

                            b1.HasIndex("DailyId");

                            b1.ToTable("WeeklyReinforcementWeakDailies", (string)null);

                            b1.HasOne("Focadu.Domain.Dailies.Daily", null)
                                .WithMany()
                                .HasForeignKey("DailyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("WeeklyReinforcementId");
                        });

                    b.Navigation("_weakDailyLinks");
                });

            modelBuilder.Entity("Focadu.Domain.Activities.DailyActivity", b =>
                {
                    b.Navigation("QuizOptions");

                    b.Navigation("Responses");

                    b.Navigation("RoleplayNodes");
                });

            modelBuilder.Entity("Focadu.Domain.Activities.RoleplayNode", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Focadu.Domain.Courses.Course", b =>
                {
                    b.Navigation("Monthlies");
                });

            modelBuilder.Entity("Focadu.Domain.Dailies.Daily", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Focadu.Domain.Monthlies.Monthly", b =>
                {
                    b.Navigation("Weeklies");
                });

            modelBuilder.Entity("Focadu.Domain.Weeklies.Weekly", b =>
                {
                    b.Navigation("CuratedContents");

                    b.Navigation("Dailies");

                    b.Navigation("Project");

                    b.Navigation("Reinforcements");
                });
#pragma warning restore 612, 618
        }
    }
}
